### ISSUE TITLE
When tokens.txt doesn't exist in DEMO.ipynb file directory, throws error

### ISSUE THREAD

**Issue by natewalton** [BrandwatchLtd/api_sdk#1]

**Comment by anthonybu** [comment]
https://github.com/BrandwatchLtd/api_sdk/pull/2

**Comment by natewalton** [comment]
hey @anthonybu nice, thanks! I like the BWRequest clarification on the params, thanks for the PEPs. @amybarker looks like would be nice to pull.

Odd thing is that I can only create this error when I run the notebook in the directory where I cloned the repo. Run the notebook on desktop or anywhere else and it works just fine.
