### ISSUE TITLE
no attribute in get_mention_page

### ISSUE THREAD

**Issue by mamut86** [BrandwatchLtd/api_sdk#11]
I am getting the following error when using the function get_mentions from the BWQueries class in v.1.0.6:

`line 181, in get_mentions
    next_mentions = self.get_mentions_page(params, 0)
AttributeError: 'BWQueries' object has no attribute 'get_mentions_page'`

I couldn't quite figure out what causes the error but when I used the previous version of bwresources.py (that has been updated on 5. July by @pwsiegel) it works.

I am using the simplest "get_mentions" call (only name, startDate, EndDate and no filters).

**Comment by pwsiegel** [comment]
Arg, that's on me.  I'll try to fix it right now - sorry!

**Comment by mamut86** [comment]
Brilliant, thanks a lot for this quick fix!

**Comment by mamut86** [comment]
Sorry for bothering again but I have now this error couple lines more down...

`File "C:\Anaconda3\lib\site-packages\bwresources.py", line 191, in get_mentions
    next_end_date = min(mention["date"] for mention in next_mentions)

TypeError: unorderable types: NoneType() < NoneType()`

As I can see this has also been updated since v.1.0.5

**Comment by pwsiegel** [comment]
Hi!
Apologies for the belated reply, but this should all be fixed in 1.0.7.  The problem had to do with data access for different token types, and we ultimately had to go back to using page numbers.

**Comment by mamut86** [comment]
Thanks a lot for this - works perfect now.
