### ISSUE TITLE
Allowing lists of startDates in "get_mentions"

### ISSUE THREAD

**Issue by mamut86** [BrandwatchLtd/api_sdk#12]
I was wondering whether it would be possible of having the option to feed in a list of start dates (and potentially end dates) in to a "get_mentions" call.

As I understood, at the moment I can feed in a list of names but they will all have the same start and end date. For the task I am trying to achieve each query would have a different start date.

For now I will use a loop for each query but was wondering whether the performance would be better when submitting fewer requests.

**Comment by pwsiegel** [comment]
I don't think we intended to support lists of names in `get_mentions` calls; indeed, I got a `TypeError` when I tried it a moment ago.  I believe the `/data/mentions` endpoint (which is what `get_mentions` hits) supports only one query/group ID at a time, so I don't think we could actually reduce the number of requests.

So your approach is as efficient as anything we can come up with.  We've been toying with the idea of implementing some sort of batch request queue which would allow the user to chain together multiple requests for complex tasks; would something like that be useful?

**Comment by mamut86** [comment]
Thanks for the quick response. To be fair I haven't tried using a list() element in call yet but the help file is mentioning names can be list() element. That's why I assumed it will work in a batch request style. 

I am happy with using a simple loop for the moment. The task I am looking at is not very complex but it is large (6000+ queries to download). However, as this is for a research project I might not run the script very often and speed is not that crucial.
