### ISSUE TITLE
Does the parameter: Exclude Category can be used in the API? 

### ISSUE THREAD

**Issue by nhat2008** [BrandwatchLtd/api_sdk#45]
In the DashBoard UI, we can easy to filter the categories by using the field: **Filter By Category** and **Exclude Category** , but in the example for API, i can see only parentCategory and Category (maybe they are representing for the field: **Filter By Category**). Where can i put **Exclude Category** in the API?
Thanks

**Comment by nhat2008** [comment]
Sorry, i just figured out that the parameter: xCategory is standing for Exclude Category.
Please, close this ticket!
Thanks

**Comment by amybarker** [comment]
Glad you worked it out, and sorry for the slow response!
