### ISSUE TITLE
from authenticate import authenticate

### ISSUE THREAD

**Issue by alexisrolland** [BrandwatchLtd/api_sdk#73]
Hello,
I installed the `bwapi` package in my Python3 environment. Example:
```
(bw) alexis@linux:~/brandwatch$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
bwapi (3.2.0)
certifi (2018.11.29)
chardet (3.0.4)
idna (2.8)
pip (9.0.1)
pkg-resources (0.0.0)
requests (2.21.0)
setuptools (39.0.1)
urllib3 (1.24.1)
```

However, when I run the following code coming from `DEMO.ipynb` it tells me that I am missing the package `authenticate`.

```
(bw) alexis@linux:~/brandwatch$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from authenticate import authenticate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'authenticate'
```

Could you please tell me what am I missing?
Thanks

Alexis

**Comment by alexisrolland** [comment]
Ok I understand my problem.
It's because I only ran `pip install bwapi` but I did not copy the `api_sdk` repository in my project folder, so I did not have the `authenticate.py` file.

**Comment by bw-matthew** [comment]
Yeah the authenticate module is not listed in the setup.py [py_modules](https://github.com/BrandwatchLtd/api_sdk/blob/master/setup.py#L32) section.

**Comment by bw-matthew** [comment]
You can just create a BWUser object with the credentials to access the API.

**Comment by alexisrolland** [comment]
Is this on purpose or is it a mistake?
I think either `DEMO.ipynb` should be modified according to what you say, or `setup.py` should be modified to include `authenticate` and align with `DEMO.ipynb`. What do you think?

**Comment by bw-matthew** [comment]
Yeah I think that updating DEMO.py to use BWUser directly would be a good idea. I think the authenticate script is more of a convenience script.

**Comment by bw-matthew** [comment]
@alexisrolland I have created https://github.com/BrandwatchLtd/api_sdk/pull/74 to update the DEMO notebook. I've also made the authenticate script part of the installation.
