### ISSUE TITLE
Duplicate resource name in BWResource.ids 

### ISSUE THREAD

**Issue by Miraliu** [BrandwatchLtd/api_sdk#82]
In https://github.com/BrandwatchLtd/api_sdk/blob/2a9457f5e709439d1290268c626e40e2549285de/bwapi/bwresources.py#L53
When populating .ids attribute of a BWResource, the resource name is being used as key. However, resource name is not guaranteed to be unique now that a regular Query and a Logo Query may share the same name.

**Comment by hamishmorgan** [comment]
Hi Miraliu. Thanks for raising this. We're looking into it and will get back to you.

**Comment by pfairfax1** [comment]
Hi Mira, thanks again for raising this issue - we are currently working on a resolution.
