### ISSUE TITLE
filter zero value when retrieve dimension data

### ISSUE THREAD

**Issue by yonghe0901** [BrandwatchLtd/api_sdk#88]
Hello,

I have the question when calling the API the JSON including the data which the value is zero or negative for some dimensions. For example, when I use the below endpoint to retrieve the aggregated data.
https://api.brandwatch.com/projects/xxxxxx/data/forumPosts/languages/days?queryId=111&startDate=2019-10-04&endDate=2019-10-05
Please see the example JSON data, the value is zero.
{"dimension1":"languages","dimension2":"days","aggregate":"forumPosts","results":[{"id":"en","name":"English","data":{},"values":[{"id":"2019-10-04T00:00:00.000+0000","name":"2019-10-04 00:00:00.0","data":{},"value":0}]}]}

Is it possible to filter the zero and negative values with some parameters?

Thank you,
Yonghe

**Comment by yonghe0901** [comment]
I know I can discard the row which has value zero using dataFrame, I am just curious if the API can handle this then I can reduce the API call number.

**Comment by hamishmorgan** [comment]
Hello,

Sadly it's not currently possible to filter those values out on the API side of things, and there's no immediate plans for that to change. You'll have to keep filtering you data frames. Sorry I couldn't be more helpful.

Best,

Hamish

**Comment by yonghe0901** [comment]
> Hello,
> 
> Sadly it's not currently possible to filter those values out on the API side of things, and there's no immediate plans for that to change. You'll have to keep filtering you data frames. Sorry I couldn't be more helpful.
> 
> Best,
> 
> Hamish

Thanks for the reply, anyways.
